markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
exclude: ["vendor", "serve"]
collections:
    projects:
        output: true
        permalink: /projects/:path/

defaults:
    -
      scope:
          path: "projects"
      values:
          layout: "project"
          stylesheets: ["project"]

url:
baseurl:

redcarpet:
  extensions: ["strikethrough", "tables", "footnotes", "fenced_code_block", "autolink"]

sass:
  sass_dir: public/css
  style: :compressed
