markdown: redcarpet
highlighter: null
permalink: /:title
exclude: ["vendor", "serve"]

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables, footnotes]

sass:
  sass_dir: public/css
  style: :compressed
