markdown: redcarpet
highlighter: pygments
permalink: /blog/:title
exclude: ["vendor", "serve"]

url:
baseurl:

redcarpet:
  extensions: ["strikethrough", "tables", "footnotes", "fenced_code_block", "autolink"]

sass:
  sass_dir: public/css
  style: :compressed
